version: "3.9"

services:

  mongo:
    image: mongo:7
    container_name: fraud-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fraud-net

  redis:
    image: redis:7-alpine
    container_name: fraud-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fraud-net

  ml-service:
    build: ./ml-service
    container_name: fraud-ml-service
    ports:
      - "8000:8000"
    networks:
      - fraud-net

  api-gateway:
    build: ./api-gateway
    container_name: fraud-api-gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/fraud
      - REDIS_URI=redis://redis:6379
      - ML_SERVICE_URL=http://ml-service:8000
      - JWT_SECRET=supersecretminimum32charactersforjwt
      - JWT_EXPIRES_IN=1h
    depends_on:
      - mongo
      - redis
      - ml-service
    networks:
      - fraud-net

  frontend:
    build: ./frontend
    container_name: fraud-frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    networks:
      - fraud-net

networks:
  fraud-net:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
